import type { Metadata } from "next";
import { Geist_Mono, Mona_Sans } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Toaster } from "sonner";
import ErrorBoundary from "@/components/error-boundary";
import RefreshButton from "@/features/root-layout/refresh-button";
import MainLayout from "../components/main-layout";

const fontSans = Mona_Sans({
	variable: "--font-mono-sans",
	subsets: ["latin"],
});

const fontMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next Beta",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className="bg-[#E5E5E5] h-[100svh]" lang="en">
			<body
				className={`${fontSans.variable} ${fontMono.variable} antialiased h-full overflow-y-auto bg-[#E5E5E5]`}
			>
				<Script
					strategy="afterInteractive"
					src="https://unpkg.com/markdown-it@14.1.0/dist/markdown-it.min.js"
				/>
				<Script
					strategy="afterInteractive"
					src="https://unpkg.com/adaptivecards@3.0.4/dist/adaptivecards.min.js"
				/>
				{/* <!-- Adaptive Cards Base Styles --> */}
				<link
					precedence="default"
					rel="stylesheet"
					href="https://unpkg.com/adaptivecards@3.0.4/dist/adaptivecards.css"
				/>

				{/* <!-- Carousel Styles (IMPORTANT!) --> */}
				<link
					precedence="default"
					rel="stylesheet"
					href="https://unpkg.com/adaptivecards@3.0.4/dist/adaptivecards-carousel.css"
				/>
				<ErrorBoundary
					fallback={
						<div className="min-h-screen flex items-center justify-center p-4">
							<div className="text-center">
								<h1 className="text-2xl font-bold text-gray-900 mb-4">
									Oops! Something went wrong
								</h1>
								<p className="text-gray-600 mb-6">
									We apologize for the inconvenience. Please try refreshing the
									page.
								</p>
								<RefreshButton />
							</div>
						</div>
					}
				>
					<MainLayout>{children}</MainLayout>
					<Toaster />
				</ErrorBoundary>
			</body>
		</html>
	);
}
