import type { Metadata } from "next";
import { Geist_Mono, Mona_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ErrorBoundary from "@/components/error-boundary";
import RefreshButton from "@/features/root-layout/refresh-button";
import MainLayout from "../components/main-layout";

const geistSans = Mona_Sans({
	variable: "--font-mono-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next Beta",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className="bg-[#E5E5E5] h-[100svh]" lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-full overflow-y-auto bg-[#E5E5E5]`}
			>
				<ErrorBoundary
					fallback={
						<div className="min-h-screen flex items-center justify-center p-4">
							<div className="text-center">
								<h1 className="text-2xl font-bold text-gray-900 mb-4">
									Oops! Something went wrong
								</h1>
								<p className="text-gray-600 mb-6">
									We apologize for the inconvenience. Please try refreshing the
									page.
								</p>
								<RefreshButton />
							</div>
						</div>
					}
				>
					<MainLayout>{children}</MainLayout>
					<Toaster />
				</ErrorBoundary>
			</body>
		</html>
	);
}
